"""
git_agent.fleet.researcher — Cross-repo research patterns.

Provides tools for:
    - Cross-repo analysis patterns
    - Finding integration opportunities
    - Analyzing dependency graphs
    - Generating research reports
"""

from __future__ import annotations

import logging
import re
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Set, Tuple

logger = logging.getLogger(__name__)


@dataclass
class DependencyNode:
    """A node in the dependency graph."""
    name: str
    repo: str
    deps: List[str] = field(default_factory=list)
    dependents: List[str] = field(default_factory=list)
    language: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class IntegrationOpportunity:
    """A potential integration between repos."""
    repo_a: str
    repo_b: str
    shared_deps: List[str] = field(default_factory=list)
    shared_language: str = ""
    description: str = ""
    impact: str = "medium"  # low, medium, high


@dataclass
class ResearchFinding:
    """A finding from cross-repo research."""
    category: str
    title: str
    description: str
    repos: List[str] = field(default_factory=list)
    impact: str = "medium"
    recommendation: str = ""


@dataclass
class ResearchReport:
    """A complete research report."""
    title: str
    generated_at: str = ""
    repos_analyzed: int = 0
    findings: List[ResearchFinding] = field(default_factory=list)
    integrations: List[IntegrationOpportunity] = field(default_factory=list)
    dependency_graph_summary: str = ""

    def to_markdown(self) -> str:
        """Render the report as Markdown."""
        parts = [
            f"# {self.title}\n",
            f"**Generated:** {self.generated_at}\n",
            f"**Repos Analyzed:** {self.repos_analyzed}\n",
        ]

        if self.findings:
            parts.append("\n## Findings\n")
            for i, f in enumerate(self.findings, 1):
                parts.append(
                    f"\n### {i}. [{f.category}] {f.title}\n\n"
                    f"{f.description}\n\n"
                    f"**Repos:** {', '.join(f.repos)}\n"
                    f"**Impact:** {f.impact}\n"
                )
                if f.recommendation:
                    parts.append(f"**Recommendation:** {f.recommendation}\n")

        if self.integrations:
            parts.append("\n## Integration Opportunities\n")
            for i, opp in enumerate(self.integrations, 1):
                parts.append(
                    f"\n### {i}. {opp.repo_a} ↔ {opp.repo_b}\n\n"
                    f"{opp.description}\n"
                )
                if opp.shared_deps:
                    parts.append(f"**Shared Dependencies:** {', '.join(opp.shared_deps)}\n")
                if opp.shared_language:
                    parts.append(f"**Language:** {opp.shared_language}\n")
                parts.append(f"**Impact:** {opp.impact}\n")

        if self.dependency_graph_summary:
            parts.append(f"\n## Dependency Graph\n\n{self.dependency_graph_summary}\n")

        parts.append("\n---\n*Report generated by git-agent.*\n")
        return "\n".join(parts)


class FleetResearcher:
    """Cross-repo research and analysis engine.

    Parameters
    ----------
    github:
        A GitHub API client.
    fleet_org:
        Fleet organization name.
    """

    def __init__(self, github: Any, fleet_org: str) -> None:
        self.github = github
        self.fleet_org = fleet_org

    # ------------------------------------------------------------------
    # Cross-repo analysis
    # ------------------------------------------------------------------

    def analyze_repos(
        self, repos: Optional[List[str]] = None, max_repos: int = 20
    ) -> Dict[str, Dict[str, Any]]:
        """Analyze multiple repos for patterns and metadata.

        Parameters
        ----------
        repos:
            List of ``owner/repo`` strings. If None, uses org repos.
        max_repos:
            Maximum number of repos to analyze.

        Returns
        -------
        Dict mapping repo name → analysis dict.
        """
        if repos is None:
            raw_repos = self.github.list_org_repos(self.fleet_org)
            repos = [r.get("full_name", "") for r in raw_repos if r.get("full_name")]

        repos = repos[:max_repos]
        analysis: Dict[str, Dict[str, Any]] = {}

        for repo_full in repos:
            if "/" not in repo_full:
                continue
            owner, repo = repo_full.split("/", 1)

            try:
                repo_data: Dict[str, Any] = {
                    "name": repo_full,
                    "language": "",
                    "files": [],
                    "dependencies": [],
                    "entry_points": [],
                    "has_tests": False,
                    "has_ci": False,
                    "has_docs": False,
                }

                # Get repo info
                repo_info = self.github.get_repo(owner, repo)
                repo_data["language"] = repo_info.get("language", "")
                repo_data["description"] = repo_info.get("description", "")
                repo_data["topics"] = repo_info.get("topics", [])

                # List root files
                try:
                    root_files = self.github.list_files(owner, repo)
                    file_names = [f.get("name", "") for f in root_files if f.get("type") == "file"]
                    repo_data["files"] = file_names

                    # Detect features
                    repo_data["has_tests"] = any(
                        n in file_names
                        for n in ("pytest.ini", "pyproject.toml", "test", "tests", "__tests__")
                    )
                    repo_data["has_ci"] = any(
                        n in file_names or ".github" in [f.get("name", "") for f in root_files if f.get("type") == "dir"]
                        for n in (".travis.yml", ".circleci", "azure-pipelines.yml")
                    )
                    repo_data["has_docs"] = any(
                        n in file_names
                        for n in ("README.md", "docs", "mkdocs.yml", "sphinx")
                    )

                    # Detect CI in .github
                    for f in root_files:
                        if f.get("type") == "dir" and f.get("name") == ".github":
                            repo_data["has_ci"] = True

                except Exception as exc:
                    logger.debug("Could not list files for %s: %s", repo_full, exc)

                # Extract dependencies from common files
                for dep_file, dep_type in [
                    ("requirements.txt", "pip"),
                    ("pyproject.toml", "python"),
                    ("package.json", "npm"),
                    ("Cargo.toml", "cargo"),
                    ("go.mod", "go"),
                ]:
                    try:
                        content = self.github.get_file_contents(owner, repo, dep_file)
                        if content:
                            deps = self._extract_dependencies(content, dep_type)
                            repo_data["dependencies"].extend(deps)
                    except Exception:
                        pass

                # Deduplicate deps
                repo_data["dependencies"] = list(dict.fromkeys(repo_data["dependencies"]))

                analysis[repo_full] = repo_data

            except Exception as exc:
                logger.debug("Could not analyze %s: %s", repo_full, exc)
                analysis[repo_full] = {"name": repo_full, "error": str(exc)}

        return analysis

    def _extract_dependencies(self, content: str, dep_type: str) -> List[str]:
        """Extract dependency names from a dependency file."""
        deps: List[str] = []

        if dep_type == "pip":
            for line in content.splitlines():
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                # Extract package name (before any version specifier)
                m = re.match(r"^([a-zA-Z0-9_-]+)", line)
                if m:
                    deps.append(m.group(1))

        elif dep_type == "npm":
            # Try to parse JSON
            try:
                import json
                data = json.loads(content)
                for section in ("dependencies", "devDependencies"):
                    if section in data:
                        deps.extend(data[section].keys())
            except (json.JSONDecodeError, TypeError):
                pass

        elif dep_type == "python":
            # pyproject.toml - simple regex for dependencies
            for m in re.finditer(r'([a-zA-Z0-9_-]+)\s*[=<>!~]', content):
                name = m.group(1)
                if name.lower() not in ("python", "requires", "build-system"):
                    deps.append(name)

        elif dep_type == "cargo":
            for line in content.splitlines():
                line = line.strip()
                if line.startswith("#"):
                    continue
                m = re.match(r'^([a-zA-Z0-9_-]+)\s*=', line)
                if m and m.group(1) != "package":
                    deps.append(m.group(1))

        elif dep_type == "go":
            for line in content.splitlines():
                line = line.strip()
                m = re.match(r'^\t([a-zA-Z0-9_.-]+)\s+v', line)
                if m:
                    deps.append(m.group(1))

        return deps

    # ------------------------------------------------------------------
    # Integration opportunities
    # ------------------------------------------------------------------

    def find_integrations(
        self, analysis: Dict[str, Dict[str, Any]]
    ) -> List[IntegrationOpportunity]:
        """Find integration opportunities between repos."""
        opportunities: List[IntegrationOpportunity] = []
        repo_list = list(analysis.keys())

        # Build dependency map
        dep_map: Dict[str, Set[str]] = {}
        lang_map: Dict[str, List[str]] = defaultdict(list)

        for repo, data in analysis.items():
            if "error" in data:
                continue
            for dep in data.get("dependencies", []):
                dep_map.setdefault(dep, set()).add(repo)
            lang = data.get("language", "")
            if lang:
                lang_map[lang].append(repo)

        # Find shared dependencies
        for dep, repos_with_dep in dep_map.items():
            if len(repos_with_dep) < 2:
                continue
            repo_pairs = list(repos_with_dep)
            for i in range(len(repo_pairs)):
                for j in range(i + 1, len(repo_pairs)):
                    a, b = repo_pairs[i], repo_pairs[j]
                    # Check if we already have an entry for this pair
                    existing = next(
                        (o for o in opportunities if
                         {o.repo_a, o.repo_b} == {a, b}),
                        None,
                    )
                    if existing:
                        existing.shared_deps.append(dep)
                    else:
                        shared_lang = ""
                        a_lang = analysis.get(a, {}).get("language", "")
                        b_lang = analysis.get(b, {}).get("language", "")
                        if a_lang and a_lang == b_lang:
                            shared_lang = a_lang

                        opportunities.append(IntegrationOpportunity(
                            repo_a=a,
                            repo_b=b,
                            shared_deps=[dep],
                            shared_language=shared_lang,
                            description=f"Both repos depend on '{dep}' — potential for shared library or interface standardization.",
                        ))

        # Sort by number of shared deps (most opportunities first)
        opportunities.sort(key=lambda o: len(o.shared_deps), reverse=True)
        return opportunities

    # ------------------------------------------------------------------
    # Dependency graph
    # ------------------------------------------------------------------

    def build_dependency_graph(
        self, analysis: Dict[str, Dict[str, Any]]
    ) -> Dict[str, DependencyNode]:
        """Build a dependency graph across repos.

        Returns a dict mapping repo name → DependencyNode.
        """
        graph: Dict[str, DependencyNode] = {}
        dep_to_repos: Dict[str, List[str]] = defaultdict(list)

        # Build initial nodes
        for repo, data in analysis.items():
            if "error" in data:
                continue
            graph[repo] = DependencyNode(
                name=repo,
                repo=repo,
                deps=data.get("dependencies", []),
                language=data.get("language", ""),
                metadata={
                    "has_tests": data.get("has_tests", False),
                    "has_ci": data.get("has_ci", False),
                    "has_docs": data.get("has_docs", False),
                },
            )
            for dep in data.get("dependencies", []):
                dep_to_repos[dep].append(repo)

        # Link dependents
        for dep, repos in dep_to_repos.items():
            for repo_a in repos:
                for repo_b in repos:
                    if repo_a != repo_b and repo_b not in graph[repo_a].dependents:
                        graph[repo_a].dependents.append(repo_b)

        return graph

    def summarize_dependency_graph(
        self, graph: Dict[str, DependencyNode]
    ) -> str:
        """Generate a text summary of the dependency graph."""
        if not graph:
            return "No dependency data available."

        lines = ["### Most Shared Dependencies\n"]

        # Count dep usage
        dep_count: Dict[str, int] = defaultdict(int)
        for node in graph.values():
            for dep in node.deps:
                dep_count[dep] += 1

        # Top 10 shared deps
        sorted_deps = sorted(dep_count.items(), key=lambda x: x[1], reverse=True)[:10]
        for dep, count in sorted_deps:
            lines.append(f"- **{dep}**: used in {count} repo(s)")

        # Language distribution
        lang_count: Dict[str, int] = defaultdict(int)
        for node in graph.values():
            if node.language:
                lang_count[node.language] += 1

        if lang_count:
            lines.append("\n### Language Distribution\n")
            for lang, count in sorted(lang_count.items(), key=lambda x: x[1], reverse=True):
                lines.append(f"- **{lang}**: {count} repo(s)")

        # Repo connectivity
        lines.append("\n### Repo Connectivity\n")
        for name, node in sorted(graph.items()):
            conn = len(node.dependents) + len(node.deps)
            lines.append(f"- `{name}`: {len(node.deps)} deps, {len(node.dependents)} dependents, language={node.language or 'N/A'}")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Research reports
    # ------------------------------------------------------------------

    def generate_report(
        self,
        repos: Optional[List[str]] = None,
        title: str = "Fleet Research Report",
    ) -> ResearchReport:
        """Generate a comprehensive research report.

        Analyzes repos, finds integrations, builds dependency graph,
        and compiles findings.
        """
        analysis = self.analyze_repos(repos)
        integrations = self.find_integrations(analysis)
        graph = self.build_dependency_graph(analysis)

        # Generate findings
        findings = self._generate_findings(analysis, integrations, graph)

        report = ResearchReport(
            title=title,
            generated_at=datetime.now(timezone.utc).isoformat(),
            repos_analyzed=len(analysis),
            findings=findings,
            integrations=integrations,
            dependency_graph_summary=self.summarize_dependency_graph(graph),
        )

        return report

    def _generate_findings(
        self,
        analysis: Dict[str, Dict[str, Any]],
        integrations: List[IntegrationOpportunity],
        graph: Dict[str, DependencyNode],
    ) -> List[ResearchFinding]:
        """Generate research findings from analysis data."""
        findings: List[ResearchFinding] = []

        # Finding: repos without tests
        untested = [
            name for name, data in analysis.items()
            if not data.get("error") and not data.get("has_tests", False)
        ]
        if untested:
            findings.append(ResearchFinding(
                category="quality",
                title="Repos without test infrastructure",
                description=f"{len(untested)} repo(s) lack test infrastructure, increasing risk of regressions.",
                repos=untested,
                impact="high",
                recommendation="Add test frameworks and baseline tests to these repos.",
            ))

        # Finding: repos without CI
        no_ci = [
            name for name, data in analysis.items()
            if not data.get("error") and not data.get("has_ci", False)
        ]
        if no_ci:
            findings.append(ResearchFinding(
                category="devops",
                title="Repos without CI/CD",
                description=f"{len(no_ci)} repo(s) lack CI/CD pipelines.",
                repos=no_ci,
                impact="medium",
                recommendation="Set up GitHub Actions for automated testing and deployment.",
            ))

        # Finding: integration opportunities
        if integrations:
            high_impact = [i for i in integrations if len(i.shared_deps) >= 3]
            if high_impact:
                findings.append(ResearchFinding(
                    category="integration",
                    title="High-coupling repos found",
                    description=f"{len(high_impact)} repo pair(s) share 3+ dependencies — candidates for shared libraries.",
                    repos=list({i.repo_a for i in high_impact} | {i.repo_b for i in high_impact}),
                    impact="high",
                    recommendation="Consider extracting shared dependencies into internal packages.",
                ))

        # Finding: repos without docs
        no_docs = [
            name for name, data in analysis.items()
            if not data.get("error") and not data.get("has_docs", False)
        ]
        if no_docs:
            findings.append(ResearchFinding(
                category="documentation",
                title="Repos lacking documentation",
                description=f"{len(no_docs)} repo(s) have minimal documentation.",
                repos=no_docs,
                impact="low",
                recommendation="Add README.md and API documentation to improve discoverability.",
            ))

        return findings
